[build]
builder = "nixpacks"
buildCommand = "cd backend && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar backend/target/stock-evaluator-backend-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 