name: stockevaluator-backend
services:
- name: backend
  source_dir: /
  github:
    repo: your-username/stockevaluator.ai
    branch: main
  run_command: java -cp app:app/lib/* stockevaluator.StockEvaluatorApplication
  environment_slug: java
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  - key: SERVER_PORT
    value: "8080"
  - key: SPRING_DATASOURCE_URL
    value: ${DATABASE_URL}
  - key: SPRING_DATASOURCE_USERNAME
    value: ${DATABASE_USERNAME}
  - key: SPRING_DATASOURCE_PASSWORD
    value: ${DATABASE_PASSWORD}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: REDDIT_CLIENT_ID
    value: ${REDDIT_CLIENT_ID}
  - key: REDDIT_CLIENT_SECRET
    value: ${REDDIT_CLIENT_SECRET}
  - key: REDDIT_USERNAME
    value: ${REDDIT_USERNAME}
  - key: REDDIT_PASSWORD
    value: ${REDDIT_PASSWORD}
  - key: FRONTEND_URL
    value: ${FRONTEND_URL}
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3 