export { default as Textarea } from './Textarea.vue'

/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Krisefikser API
 * API for the Krisefikser application
 * OpenAPI spec version: 1.0
 */

export interface CreateHouseholdInviteRequest {
  email: string;
  householdId: string;
}
